name: Deploy Application

on:
  push:
    branches:
      - main
env:
        PR_NUMBER: "456"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Create Git tag for PR
        uses: actions/github-script@v4
        with:
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/0.0.0-pr${{env.PR_NUMBER}}",
              sha: context.sha
            })