name: GitVersion

on:
  push:
    branches:
      - main

env:
    PR_NUMBER: "456"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get year
        run: |
          echo "VERSION_MAJOR=$(date +'%Y')" >> $GITHUB_OUTPUT
        id: year  # this is used on variable path

      - name: Get week
        run: |
          echo "VERSION_MINOR=$(date +'%V')" >> $GITHUB_OUTPUT
        id: week  # this is used on variable path

      - name: print date
        run: |
          echo $DEBUG
        env:
          YEAR: ${{ steps.year.outputs.year }}
          WEEK: ${{  steps.week.outputs.week }}

      - name: Generate Git Tag
        id: generate_tag
        run: |
          VERSION_PREFIX="v"
          VERSION_MAJOR_MINOR=${{ steps.year.outputs.VERSION_MAJOR }}.${{  steps.week.outputs.VERSION_MINOR }}
          VERSION_PATCH=$(git tag --list "${VERSION_PREFIX}${VERSION_MAJOR_MINOR}.*" --sort=-version:refname | head -n 1 | grep -oE '[0-9]+$')
          if [ -z "$VERSION_PATCH" ]; then
            VERSION_PATCH=0
          else
            VERSION_PATCH=$((VERSION_PATCH + 1))
          fi
          NEW_TAG="${VERSION_PREFIX}${VERSION_MAJOR_MINOR}.${VERSION_PATCH}"
          echo "Generated new tag: $NEW_TAG"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV
          
      - name: Create Git tag for PR
        uses: actions/github-script@v4
        with:
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/v${{ steps.year.outputs.VERSION_MAJOR }}.${{  steps.week.outputs.VERSION_MINOR }}",
              sha: context.sha
            })