name: GitVersion

on:
  push:
    branches:
      - main

env:
    PR_NUMBER: "456"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get year
        run: |
          echo "year=$(date +'%Y')" >> $GITHUB_OUTPUT
        id: year  # this is used on variable path

      - name: Get week
        run: |
          echo "week=$(date +'%V')" >> $GITHUB_OUTPUT
        id: week  # this is used on variable path

      - name: print date
        run: |
          echo $DEBUG
        env:
          YEAR: ${{ steps.year.outputs.year }}
          WEEK: ${{  steps.week.outputs.week }}